import type {Metadata} from "next";
import Head from "next/head";
import {Inter} from "next/font/google";
import "./globals.css";
import Header from "@/app/pages/header/page";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Отдел МО",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <>
            <Head>
                <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
            </Head>
            <html lang="en">
                <body className={inter.className}>
                    <Header/>
                    {children}
                </body>
            </html>
        </>
    );
}
